name: Releases

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
         artifacts: "release.zip"
         token: ${{ secrets.GITHUB_TOKEN }}
